primary_location       = "West US"
image_name             = "minecraft-bedrock-local"
image_version          = "1.0.2"
gallery_resource_group = "rg-aztf-machine-images-dev"
gallery_name           = "galaztfmachineimagesdev"