# Refer ./setup/baseConfig.yaml for full set of config parameters

allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /tmp/minecraft/worlds
  timeout-sec: 120
  max-size-mb: 4096
  cleanup-on-start: false

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: AZURE_STORAGE_ACCOUNT_NAME
  endpoint: https://AZURE_STORAGE_ACCOUNT_NAME.blob.core.windows.net
  mode: msi
  container: AZURE_STORAGE_CONTAINER_NAME
 